/mnt/c/Users/samschillace/amplifier/.venv/bin/python3: can't open file '/mnt/c/Users/samschillace/amplifier/test_vi_torture.py': [Errno 2] No such file or directory
